### ISSUE TITLE
Sense2GoL

### ISSUE THREAD

**Issue by ironstrike** [Infineon/24GHz-Radar-for-Arduino#2]
Hi, I'm using Sense2GoL module for my project. I'm able to get the values from the Sense2GoL module but I want to send those values to another microcontroller like XMC1100 Bootkit. Is there any Communication protocol available in the Sense2GoL so that I can get the values from the module.

**Comment by ArkajyotiChatterjee** [comment]
Yes. Please go through this [link](https://github.com/Infineon/XMC-for-Arduino/tree/master/arm/libraries/Radar)
